# Ekstraksi Fitur

## Ekstraksi Fitur Data PTA Manajemen

In [1]:
import pandas as pd

# Load data from pta_manajemen.csv
df = pd.read_csv('pta_manajemen.csv')

In [ ]:
# Display basic information about the dataset
print("Dataset shape:", df.shape)
df

Dataset shape: (1026, 2)

,abstrak_id,hasil_preprocessing
0,Aplikasi nyata pemanfaatan teknologi informasi...,"['aplikasi', 'nyata', 'manfaat', 'teknologi', ..."
1,Tujuan penelitian ini adalah untuk mengetahui ...,"['tuju', 'teliti', 'persepsi', 'brand', 'assoc..."
2,"ABSTRAK\n\nSatiyah, Pengaruh Faktor-faktor Pel...","['abstrak', 'satiyah', 'pengaruh', 'faktorfakt..."
3,Abstrak\n\nPenelitian ini menggunakan metode k...,"['abstrak', 'teliti', 'metode', 'kuantitatif',..."
4,Hasil dari penelitian ini dari perhitungan Cre...,"['hasil', 'teliti', 'hitung', 'credit', 'risk'..."
...,...,...
1021,"ABSTRAK\nUswatun Hasanah, 160211100291, Pengar...","['abstrak', 'uswatun', 'hasanah', 'pengaruh', ..."
1022,Tujuan penelitian ini adalah untuk mengetahui ...,"['tuju', 'teliti', 'beban', 'operasional', 'da..."
1023,ABSTRAK\nPenelitian ini bertujuan: (1) Untuk m...,"['abstrak', 'teliti', 'tuju', 'baur', 'promosi..."
1024,ABSTRAK\nTujuan dari penelitian ini adalah unt...,"['abstrak', 'tuju', 'teliti', 'peran', 'servic..."
1025,Penelitian ini bertujuan untuk dapat mengetahu...,"['teliti', 'tuju', 'pengaruh', 'motivasi', 'ke..."

###  Ekstraksi Fitur TF-IDF

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
# Kolom teks hasil preprocessing
texts = df["abstrak_id"].astype(str)

# Kalau ada kolom label
labels = df["abstrak_id"]

###  TF-IDF Vectorization

In [7]:
vectorizer = TfidfVectorizer()

# Fit & transform ke matriks TF-IDF
tfidf_matrix = vectorizer.fit_transform(texts)

# Konversi ke DataFrame agar lebih mudah dibaca
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Tambahkan kolom label
tfidf_df["abstrak_id"] = labels.values

In [8]:
print("Ukuran matriks TF-IDF:", tfidf_df.shape)
tfidf_df

Ukuran matriks TF-IDF: (1031, 8745)

,00,000,000000,00007,00024,00025,00035,00081,00083,000ttabel,...,zte,zuhri,zuhruf,zulfi,zulia,zuliana,zulkifli,zulpah,zyn,abstrak_id
0,0.042293,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"ABSTRAK\r\nSatiyah, Pengaruh Faktor-faktor Pel..."
1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tujuan penelitian ini adalah untuk mengetahui ...
2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Aplikasi nyata pemanfaatan teknologi informasi...
4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Abstrak\r\nPenelitian ini menggunakan metode k...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ABSTRAK\nPenelitian ini bertujuan untuk menget...
1027,0.000000,0.069505,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"ABSTRAK\nUswatun Hasanah, 160211100291, Pengar..."
1028,0.000000,0.054559,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ABSTRAK\nTujuan dari penelitian ini adalah unt...
1029,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ABSTRAK\nPenelitian ini bertujuan: (1) Untuk m...
1030,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Penelitian ini bertujuan untuk dapat mengetahu...

In [9]:
output_file = "hasil_tfidf_pta_manajemen.xlsx"

# index=False biar tidak ikut nyimpan index dataframe
tfidf_df.to_excel(output_file, index=False)

print(f"Hasil TF-IDF berhasil disimpan ke file: {output_file}")

Hasil TF-IDF berhasil disimpan ke file: hasil_tfidf_pta_manajemen.xlsx

## Ekstraksi Fitur Data Berita

In [4]:
import pandas as pd

# Load data from hasil_preprocessing_berita.csv
df = pd.read_csv('hasil_preprocessing_berita.csv')

In [5]:
# Display basic information about the dataset
print("Dataset shape:", df.shape)
df

Dataset shape: (9000, 3)

,isi_berita,hasil_preprocessing,kategori_berita
0,BRIGADIR JenderalWahyu Yudhayanamenduduki jaba...,"['brigadir', 'jenderalwahyu', 'yudhayanamendud...",politik
1,PEMERINTAH Kota Bandung akan membentuk satuan ...,"['perintah', 'kota', 'bandung', 'bentuk', 'sat...",politik
2,PANGLIMATNIJenderal Agus Subiyanto kembali mel...,"['panglimatnijenderal', 'agus', 'subiyanto', '...",politik
3,KELOMPOK organisasi relawan pendukung Presiden...,"['kelompok', 'organisasi', 'rawan', 'dukung', ...",politik
4,STASIUN televisi swastaTrans7meminta maaf atas...,"['stasiun', 'televisi', 'swastatransmeminta', ...",politik
...,...,...,...
8995,"TEMPO.CO,Jakarta-Persija Jakartamemperkenalkan...","['tempocojakartapersija', 'jakartamemperkenalk...",sepakbola
8996,"TEMPO.CO,Hong Kong-Â Pertandingan babak pertama...","['tempocohong', 'kong', 'tanding', 'babak', 'p...",sepakbola
8997,"TEMPO.CO,Hong Kong-Â Para penggemarLiverpoolmen...","['tempocohong', 'kong', 'penggemarliverpoolmen...",sepakbola
8998,"TEMPO.CO,Jakarta- Ketua Umum PSSIErick Thohirm...","['tempocojakarta', 'ketua', 'pssierick', 'thoh...",sepakbola
8999,"TEMPO.CO,Jakarta- Ketua Umum PSSIErick Thohirm...","['tempocojakarta', 'ketua', 'pssierick', 'thoh...",sepakbola

###  Ekstraksi Fitur TF-IDF

In [6]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
# Kolom teks hasil preprocessing
texts = df["hasil_preprocessing"].astype(str)

# Kalau ada kolom label
labels = df["kategori_berita"]

###  TF-IDF Vectorization

In [8]:
vectorizer = TfidfVectorizer()

# Fit & transform ke matriks TF-IDF
tfidf_matrix = vectorizer.fit_transform(texts)

# Konversi ke DataFrame agar lebih mudah dibaca
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Tambahkan kolom label
tfidf_df["kategori_berita"] = labels.values

In [9]:
print("Ukuran matriks TF-IDF:", tfidf_df.shape)
tfidf_df

Ukuran matriks TF-IDF: (9000, 90304)

,aa,aab,aac,aaditya,aadmi,aaf,aafxs,aag,aahd,aai,...,zwiers,zwiersmendampingi,zwolle,zxr,zxrr,zyrexindo,zz,zzp,zzt,kategori_berita
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,politik
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,politik
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,politik
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,politik
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,politik
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sepakbola
8996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sepakbola
8997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sepakbola
8998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sepakbola
8999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sepakbola

In [11]:
output_file = "hasil_tfidf_berita.xlsx"

# Pilih hanya 1000 fitur TF-IDF teratas berdasarkan rata-rata skor
top_n = 1000
feature_cols = tfidf_df.columns.drop("kategori_berita")
top_features = tfidf_df[feature_cols].mean(axis=0).sort_values(ascending=False).head(top_n).index.tolist()

# Buat DataFrame baru hanya dengan fitur teratas dan kolom label
tfidf_df_top = tfidf_df[top_features + ["kategori_berita"]]

# index=False biar tidak ikut nyimpan index dataframe
tfidf_df_top.to_excel(output_file, index=False)

print(f"Hasil TF-IDF (top {top_n} fitur) berhasil disimpan ke file: {output_file}")

Hasil TF-IDF (top 1000 fitur) berhasil disimpan ke file: hasil_tfidf_berita.xlsx